services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: SOR-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT: 2181
      - ZOOKEEPER_TICK_TIME: 2000
    ports:
      -"2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: SOR-kafka
    depends_on:
      - zookeeper
    ports:
      -"9094:9094"
    environment:
      - KAFKA_BROKER_ID: 1
      - KAFKA_ZOOKEEPER_CONECT: "zookeeper:2181"
      - KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9094"
      - KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094"
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      - KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  postgres:
    image: postgres:16-alpine
    container_name: SOR-postgres
    environment:
      - POSTGRES_DB: ${POSTGRES_DB}
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      -"5432:5432"
    volumes:
      - SOR_pgdata:/var/lib/postgresql/data
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  adminer:
    image: adminer:latest
    container_name: SOR-adminer
    depends_on:
      - postgres
    ports:
      - "8081:8080"

volumes:
  SOR_pgdata